# Building
FROM golang:1.22 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux \
    go build -v \
    -o /app/server \
    ./cmd/web/main.go


FROM alpine:3.23

COPY --from=builder /app/server /usr/local/bin/server
EXPOSE 8080
ENTRYPOINT [ "/usr/local/bin/server" ]
